// Mocks generated by Mockito 5.4.5 from annotations
// in projects/test/unit/providers/preset_provider_validation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:projects/features/presets/models/preset.dart' as _i4;
import 'package:projects/features/presets/repositories/preset_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PresetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPresetRepository extends _i1.Mock implements _i2.PresetRepository {
  MockPresetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, _i4.Preset>> getAllPresets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPresets, []),
            returnValue: _i3.Future<Map<String, _i4.Preset>>.value(
              <String, _i4.Preset>{},
            ),
          )
          as _i3.Future<Map<String, _i4.Preset>>);

  @override
  _i3.Future<void> saveAllPresets(Map<String, _i4.Preset>? presets) =>
      (super.noSuchMethod(
            Invocation.method(#saveAllPresets, [presets]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addPreset(_i4.Preset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#addPreset, [preset]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePreset(_i4.Preset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreset, [preset]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePreset(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePreset, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
