// Mocks generated by Mockito 5.4.5 from annotations
// in projects/test/unit/providers/sound_test_provider_create_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:projects/features/sound_test/models/sound_test.dart' as _i4;
import 'package:projects/features/sound_test/repositories/sound_test_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SoundTestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoundTestRepository extends _i1.Mock
    implements _i2.SoundTestRepository {
  MockSoundTestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, _i4.SoundTest>> getAllSoundTests() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSoundTests, []),
            returnValue: _i3.Future<Map<String, _i4.SoundTest>>.value(
              <String, _i4.SoundTest>{},
            ),
          )
          as _i3.Future<Map<String, _i4.SoundTest>>);

  @override
  _i3.Future<void> saveAllSoundTests(Map<String, _i4.SoundTest>? soundTests) =>
      (super.noSuchMethod(
            Invocation.method(#saveAllSoundTests, [soundTests]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addSoundTest(_i4.SoundTest? soundTest) =>
      (super.noSuchMethod(
            Invocation.method(#addSoundTest, [soundTest]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSoundTest(_i4.SoundTest? soundTest) =>
      (super.noSuchMethod(
            Invocation.method(#updateSoundTest, [soundTest]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSoundTest(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSoundTest, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
